service: handover-sls

provider:
  name: google
  runtime: nodejs
  project: graphical-petal-169116
  credentials: ~/.gcloud/keyfile-handover.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-webpack

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  auth:
    handler: auth
    events:
      - http: auth
